<?php

namespace Database\Seeders;

use App\Enums\WorkPackageNameEnum;
use App\Models\WorkPackage;
use Illuminate\Database\Seeder;

class WorkPackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $workPackages = [
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 1,
                'work_id' => 1,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 1,
                'work_id' => 1,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 1,
                'work_id' => 1,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 300,
                'upper_bound_budget' => 5400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 1,
                'work_id' => 2,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 1,
                'work_id' => 2,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 23000,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 1,
                'work_id' => 2,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 2300,
                'upper_bound_budget' => 20400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 1,
                'work_id' => 3,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 2100,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 1,
                'work_id' => 3,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 2100,
                'upper_bound_budget' => 5100,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 1,
                'work_id' => 3,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 5100,
                'upper_bound_budget' => 23800,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 1,
                'work_id' => 4,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 1,
                'work_id' => 4,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 1,
                'work_id' => 4,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 300,
                'upper_bound_budget' => 7400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 2,
                'work_id' => 5,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 2,
                'work_id' => 5,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 2,
                'work_id' => 5,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 300,
                'upper_bound_budget' => 7700,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 2,
                'work_id' => 6,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 2,
                'work_id' => 6,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 2700,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 2,
                'work_id' => 6,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 2700,
                'upper_bound_budget' => 17500,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 2,
                'work_id' => 7,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 4800,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 2,
                'work_id' => 7,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 4800,
                'upper_bound_budget' => 7800,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 2,
                'work_id' => 7,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 7800,
                'upper_bound_budget' => 29500,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 2,
                'work_id' => 8,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 2,
                'work_id' => 8,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 2,
                'work_id' => 8,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 300,
                'upper_bound_budget' => 2200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 1,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 1,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 1,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 300,
                'upper_bound_budget' => 4200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 1,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 1,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 1100,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 1,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 1100,
                'upper_bound_budget' => 9700,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 1,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 2000,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 1,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 2000,
                'upper_bound_budget' => 5400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 1,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 5400,
                'upper_bound_budget' => 40800,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 1,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 1,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 1,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 300,
                'upper_bound_budget' => 5200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 1,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 1,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 1,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 300,
                'upper_bound_budget' => 5500,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 1,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 2000,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 1,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 2000,
                'upper_bound_budget' => 6200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 1,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 6200,
                'upper_bound_budget' => 17900,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 1,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 1,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 700,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 1,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 700,
                'upper_bound_budget' => 11100,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 1,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 1,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 1,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 300,
                'upper_bound_budget' => 5900,
            ],

            // Number of rooms 2
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 2,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 2,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 2,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 300,
                'upper_bound_budget' => 5400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 2,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 2,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 2300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 2,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 2300,
                'upper_bound_budget' => 10800,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 2,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 3100,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 2,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 3100,
                'upper_bound_budget' => 6500,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 2,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 6500,
                'upper_bound_budget' => 41900,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 2,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 2,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 2,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 300,
                'upper_bound_budget' => 6300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 2,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 2,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 400,
                'upper_bound_budget' => 1300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 2,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 1300,
                'upper_bound_budget' => 7100,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 2,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 3600,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 2,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 3600,
                'upper_bound_budget' => 7800,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 2,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 7800,
                'upper_bound_budget' => 19500,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 2,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 1400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 2,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 1400,
                'upper_bound_budget' => 2300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 2,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 2300,
                'upper_bound_budget' => 12700,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 2,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 700,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 2,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 700,
                'upper_bound_budget' => 1200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 2,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 1200,
                'upper_bound_budget' => 7500,
            ],

            // Number of rooms 3
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 3,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 200,
                'upper_bound_budget' => 700,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 3,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 700,
                'upper_bound_budget' => 1200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 3,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 1200,
                'upper_bound_budget' => 6500,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 3,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 300,
                'upper_bound_budget' => 1400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 3,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 1400,
                'upper_bound_budget' => 3400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 3,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 3400,
                'upper_bound_budget' => 11900,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 3,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 300,
                'upper_bound_budget' => 4300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 3,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 4300,
                'upper_bound_budget' => 7700,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 3,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 7700,
                'upper_bound_budget' => 43100,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 3,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 100,
                'upper_bound_budget' => 800,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 3,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 800,
                'upper_bound_budget' => 1400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 3,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 1400,
                'upper_bound_budget' => 7400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 3,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1300,
                'upper_bound_budget' => 1600,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 3,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 1600,
                'upper_bound_budget' => 2600,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 3,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 2600,
                'upper_bound_budget' => 8400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 3,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1300,
                'upper_bound_budget' => 4900,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 3,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 4900,
                'upper_bound_budget' => 9000,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 3,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 9000,
                'upper_bound_budget' => 20800,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 3,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1300,
                'upper_bound_budget' => 2600,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 3,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 2600,
                'upper_bound_budget' => 3600,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 3,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 3600,
                'upper_bound_budget' => 14000,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 3,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1300,
                'upper_bound_budget' => 1900,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 3,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 1900,
                'upper_bound_budget' => 2400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 3,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 2400,
                'upper_bound_budget' => 8800,
            ],

            // Number of rooms 4
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 4,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1100,
                'upper_bound_budget' => 1600,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 4,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 1600,
                'upper_bound_budget' => 2100,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 4,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 2100,
                'upper_bound_budget' => 7400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 4,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1200,
                'upper_bound_budget' => 2300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 4,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 2300,
                'upper_bound_budget' => 4300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 4,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 4300,
                'upper_bound_budget' => 12800,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 4,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1200,
                'upper_bound_budget' => 5200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 4,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 5200,
                'upper_bound_budget' => 8600,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 4,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 8600,
                'upper_bound_budget' => 44000,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 4,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1000,
                'upper_bound_budget' => 1700,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 4,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 1700,
                'upper_bound_budget' => 2300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 4,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 2300,
                'upper_bound_budget' => 8300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 4,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 700,
                'upper_bound_budget' => 2100,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 4,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 2100,
                'upper_bound_budget' => 3000,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 4,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 3000,
                'upper_bound_budget' => 8800,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 4,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1700,
                'upper_bound_budget' => 5300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 4,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 5300,
                'upper_bound_budget' => 9500,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 4,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 9500,
                'upper_bound_budget' => 21300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 4,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1800,
                'upper_bound_budget' => 3100,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 4,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 3100,
                'upper_bound_budget' => 4000,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 4,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 4000,
                'upper_bound_budget' => 14400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 4,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1700,
                'upper_bound_budget' => 2400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 4,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 2400,
                'upper_bound_budget' => 2900,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 4,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 2900,
                'upper_bound_budget' => 9200,
            ],

            // Number of rooms 4
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 5,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1600,
                'upper_bound_budget' => 2100,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 5,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 2100,
                'upper_bound_budget' => 2600,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 5,
                'work_id' => 9,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 2600,
                'upper_bound_budget' => 7900,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 5,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1700,
                'upper_bound_budget' => 2800,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 5,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 2800,
                'upper_bound_budget' => 4800,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 5,
                'work_id' => 10,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 4800,
                'upper_bound_budget' => 13300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 5,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1700,
                'upper_bound_budget' => 5700,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 5,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 5700,
                'upper_bound_budget' => 9100,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 5,
                'work_id' => 11,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 9100,
                'upper_bound_budget' => 44500,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 5,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 1500,
                'upper_bound_budget' => 2200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 5,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 2200,
                'upper_bound_budget' => 2800,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 3,
                'number_of_room' => 5,
                'work_id' => 12,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 2800,
                'upper_bound_budget' => 8800,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 5,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 5600,
                'upper_bound_budget' => 5900,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 5,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 5900,
                'upper_bound_budget' => 6900,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 5,
                'work_id' => 13,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 6900,
                'upper_bound_budget' => 12700,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 5,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 5600,
                'upper_bound_budget' => 9200,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 5,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 9200,
                'upper_bound_budget' => 13400,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 5,
                'work_id' => 14,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 13400,
                'upper_bound_budget' => 25100,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 5,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 5700,
                'upper_bound_budget' => 6900,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 5,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 6900,
                'upper_bound_budget' => 7900,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 5,
                'work_id' => 15,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 7900,
                'upper_bound_budget' => 18300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 5,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::LIGHT,
                'lower_bound_budget' => 5600,
                'upper_bound_budget' => 6300,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 5,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::MODERATE,
                'lower_bound_budget' => 6300,
                'upper_bound_budget' => 6700,
            ],
            [
                'min_property_size' => 1,
                'max_property_size' => 100,
                'room_id' => 4,
                'number_of_room' => 5,
                'work_id' => 16,
                'name' => WorkPackageNameEnum::EXTENSIVE,
                'lower_bound_budget' => 6700,
                'upper_bound_budget' => 13100,
            ],
        ];

        foreach ($workPackages as $wp) {
            WorkPackage::create($wp);
        }
    }
}
